export const HANDLE_INCREMENT_COUNT = "INCREMENT_COUNT";
export const HANDLE_DECREMENT_COUNT = "DECREMENT_COUNT";
export const HANDLE_DOTS_CLICK = "DOTS_CLICK";
export const SLIDES_LOAD_FROM_SERVER = "SLIDES_LOADED";
